export interface Product {
  id: string;
  name: string;
  description: string;
  price: number; // in cents
  category: 'boxes' | 'packing' | 'bags' | 'tape' | 'gear' | 'specialty';
  emoji: string;
  image?: string; // /products/*.svg illustration (swap for photos anytime)
  badge?: string;
  bestseller?: boolean;
  options?: string[];
}

export const products: Product[] = [
  // Boxes
  {
    id: 'box-small',
    name: 'Small Moving Box',
    description: 'Perfect for books, dishes, and heavy items. Double-wall construction for maximum strength.',
    price: 299,
    category: 'boxes',
    emoji: '📦',
    image: '/products/box-s.svg',
    options: ['Pack of 5', 'Pack of 10', 'Pack of 25'],
    bestseller: true,
  },
  {
    id: 'box-medium',
    name: 'Medium Moving Box',
    description: 'Ideal for kitchen items, toys, and clothing. Our most popular size.',
    price: 349,
    category: 'boxes',
    emoji: '📦',
    image: '/products/box-m.svg',
    options: ['Pack of 5', 'Pack of 10', 'Pack of 25'],
    badge: 'Most Popular',
  },
  {
    id: 'box-large',
    name: 'Large Moving Box',
    description: 'Great for pillows, comforters, and lightweight bulky items.',
    price: 449,
    category: 'boxes',
    emoji: '📦',
    image: '/products/box-l.svg',
    options: ['Pack of 5', 'Pack of 10'],
  },
  {
    id: 'box-xl',
    name: 'Extra-Large Moving Box',
    description: 'For large, lightweight items like lamps, sports gear, and outdoor cushions.',
    price: 549,
    category: 'boxes',
    emoji: '📦',
    image: '/products/box-xl.svg',
    options: ['Pack of 5', 'Pack of 10'],
  },
  {
    id: 'box-wardrobe',
    name: 'Wardrobe Box',
    description: 'Built-in hanging bar keeps clothes wrinkle-free. Fits a full closet section.',
    price: 1899,
    category: 'boxes',
    emoji: '👔',
    image: '/products/wardrobe.svg',
    badge: 'Premium',
  },
  {
    id: 'box-dish-pack',
    name: 'Dish Pack Box',
    description: 'Extra-thick walls with cell dividers for china, glassware, and fragile items.',
    price: 799,
    category: 'boxes',
    emoji: '🍽️',
    image: '/products/dishpack.svg',
  },

  // Packing Supplies
  {
    id: 'bubble-wrap-sm',
    name: 'Bubble Wrap Roll — Small',
    description: '12" × 30 ft roll of premium bubble wrap. Ideal for electronics and fragile items.',
    price: 1299,
    category: 'packing',
    emoji: '🫧',
    image: '/products/bubble-wrap.svg',
    bestseller: true,
  },
  {
    id: 'bubble-wrap-lg',
    name: 'Bubble Wrap Roll — Large',
    description: '24" × 50 ft heavy-duty roll for furniture and large appliances.',
    price: 2499,
    category: 'packing',
    emoji: '🫧',
    image: '/products/bubble-wrap.svg',
  },
  {
    id: 'packing-paper',
    name: 'Packing Paper — 50 Sheets',
    description: "Newsprint-free white packing paper. Won't leave ink marks on your items.",
    price: 999,
    category: 'packing',
    emoji: '📄',
    image: '/products/packing-paper.svg',
  },
  {
    id: 'foam-wrap',
    name: 'Foam Wrap Sheets — 50 Pk',
    description: 'Self-sealing foam cushioning for dishes, glasses, and collectibles.',
    price: 1499,
    category: 'packing',
    emoji: '🟪',
    image: '/products/foam-wrap.svg',
    badge: 'New',
  },
  {
    id: 'stretch-wrap',
    name: 'Stretch Wrap Roll',
    description: '15" × 1000 ft industrial shrink wrap. Locks drawers shut and bundles items without adhesive.',
    price: 1899,
    category: 'packing',
    emoji: '🌀',
    image: '/products/stretch-wrap.svg',
  },

  // Bags & Covers
  {
    id: 'mattress-bag-queen',
    name: 'Mattress Bag — Queen',
    description: 'Heavy-duty polyethylene mattress cover. Protects from dust, dirt, and moisture.',
    price: 1299,
    category: 'bags',
    emoji: '🛏️',
    image: '/products/mattress-bag.svg',
  },
  {
    id: 'mattress-bag-king',
    name: 'Mattress Bag — King',
    description: 'Extra-wide cover for king and California king mattresses.',
    price: 1599,
    category: 'bags',
    emoji: '🛏️',
    image: '/products/mattress-bag.svg',
  },
  {
    id: 'sofa-cover',
    name: 'Sofa Cover Bag',
    description: 'Stretch-wrap style cover for sofas and sectionals. Tear-resistant and waterproof.',
    price: 1999,
    category: 'bags',
    emoji: '🛋️',
    image: '/products/sofa-cover.svg',
    badge: 'Premium',
  },
  {
    id: 'tv-bag',
    name: 'Flat Screen TV Bag',
    description: 'Dual-chamber padded bag with corner protectors for screens up to 85".',
    price: 2499,
    category: 'bags',
    emoji: '📺',
    image: '/products/tv-bag.svg',
  },

  // Tape & Labels
  {
    id: 'packing-tape-3pk',
    name: 'Heavy-Duty Packing Tape — 3 Pack',
    description: '2" × 60 yd rolls of industrial-strength clear tape with dispenser.',
    price: 1099,
    category: 'tape',
    emoji: '🟨',
    image: '/products/tape.svg',
    bestseller: true,
  },
  {
    id: 'label-markers',
    name: 'Moving Labels Kit',
    description: '100 pre-printed room labels + 2 permanent markers. Color-coded by room.',
    price: 699,
    category: 'tape',
    emoji: '🏷️',
    image: '/products/labels.svg',
  },
  {
    id: 'box-cutter-2pk',
    name: 'Safety Box Cutter — 2 Pack',
    description: 'Retractable blades with auto-lock. Opens boxes fast without slicing contents.',
    price: 799,
    category: 'tape',
    emoji: '🔪',
    image: '/products/box-cutter.svg',
  },

  // Moving Gear
  {
    id: 'moving-blankets-6pk',
    name: 'Moving Blankets — 6 Pack',
    description: '72" × 80" quilted furniture pads. The same blankets our own crews use on every job.',
    price: 4999,
    category: 'gear',
    emoji: '🧵',
    image: '/products/blankets.svg',
    bestseller: true,
  },
  {
    id: 'ratchet-straps-4pk',
    name: 'Ratchet Tie-Down Straps — 4 Pack',
    description: '1" × 15 ft straps rated to 500 lb working load. Keeps loads planted in the truck.',
    price: 2499,
    category: 'gear',
    emoji: '🪢',
    image: '/products/straps.svg',
  },
  {
    id: 'furniture-sliders-16pk',
    name: 'Furniture Sliders — 16 Pack',
    description: 'Slide heavy furniture across carpet and hardwood without lifting or floor damage.',
    price: 1299,
    category: 'gear',
    emoji: '🛝',
    image: '/products/sliders.svg',
  },
  {
    id: 'work-gloves',
    name: 'Grip Work Gloves',
    description: 'Textured palm grip with breathable backing. Sized M–XL.',
    price: 999,
    category: 'gear',
    emoji: '🧤',
    image: '/products/gloves.svg',
    options: ['M', 'L', 'XL'],
  },
  {
    id: 'hand-truck',
    name: 'Folding Hand Truck',
    description: '600 lb capacity steel hand truck. Folds flat for storage — a lifetime mover.',
    price: 7999,
    category: 'gear',
    emoji: '🛒',
    image: '/products/hand-truck.svg',
    badge: 'Pro Grade',
  },

  // Bundle Kits
  {
    id: 'moving-kit-starter',
    name: 'Starter Moving Kit',
    description: '10 mixed boxes, bubble wrap, tape, labels, and packing paper. Perfect for studio apartments.',
    price: 4999,
    category: 'specialty',
    emoji: '🎁',
    image: '/products/kit.svg',
    badge: 'Bundle',
  },
  {
    id: 'moving-kit-family',
    name: 'Family Moving Kit',
    description: '30 mixed boxes, 2 wardrobe boxes, full packing supplies. Covers a 3-bedroom home.',
    price: 12999,
    category: 'specialty',
    emoji: '🏠',
    image: '/products/kit.svg',
    badge: 'Best Value',
  },
];

export const categories = [
  { value: 'all', label: 'All Products' },
  { value: 'boxes', label: 'Moving Boxes' },
  { value: 'packing', label: 'Packing Supplies' },
  { value: 'bags', label: 'Covers & Bags' },
  { value: 'tape', label: 'Tape & Tools' },
  { value: 'gear', label: 'Moving Gear' },
  { value: 'specialty', label: 'Bundle Kits' },
];
